export const RACES = [
  'Affenpinscher', 'Airedale Terrier', 'Akbash', 'Akita Américain', 'Akita Inu',
  'Alaskan Klee Kai', 'Alaskan Malamute', 'American Staffordshire Terrier (Amstaff)',
  'Anglo-Français de Petite Vènerie', 'Ariégeois',
  'Barbet', "Barzoï (Lévrier Russe)", 'Basenji',
  'Basset Artésien Normand', 'Basset Bleu de Gascogne', 'Basset Fauve de Bretagne', 'Basset Hound', 'Beagle',
  'Beauceron', 'Berger Allemand', 'Berger Australien', 'Berger Belge Groenendael',
  'Berger Belge Malinois', 'Berger Belge Tervueren', 'Berger Blanc Suisse', 'Berger de Bergame',
  'Berger de Brie (Briard)', 'Berger des Pyrénées', 'Berger des Shetland (Sheltie)',
  'Berger Hollandais', 'Berger Islandais', 'Berger Picard',
  'Bichon Bolonais', 'Bichon Frisé', 'Bichon Havanais', 'Bloodhound (Saint-Hubert)', 'Bobtail (Old English Sheepdog)',
  'Border Collie', 'Border Terrier', 'Boston Terrier',
  'Bouledogue Américain', 'Bouledogue Anglais', 'Bouledogue Français',
  'Bouvier Australien', 'Bouvier Bernois', "Bouvier de l'Appenzell", "Bouvier de l'Entlebuch",
  'Bouvier des Ardennes', 'Bouvier des Flandres', 'Boxer', 'Braque Allemand (Drathaar)',
  "Braque d'Auvergne", 'Braque de Burgos', 'Braque de Weimar', 'Braque du Bourbonnais',
  'Braque Français', 'Braque Hongrois (Magyar Vizsla)', 'Braque Italien', 'Braque Portugais',
  'Briquet Griffon Vendéen', 'Buhund Norvégien', 'Bull Mastiff', 'Bull Terrier', 'Bull Terrier Miniature',
  'Cairn Terrier', 'Cane Corso', 'Caniche',
  'Carlin (Pug)', 'Cavalier King Charles', 'Chien Chinois à Crête',
  "Chien d'Eau Espagnol", "Chien d'Eau Irlandais", "Chien d'Eau Portugais (Cao de Agua)",
  'Chien de Canaan', "Chien de la Réunion (Bourbon Créole)", "Chien de Montagne de l'Atlas (Aidi)",
  "Chien d'Élan Norvégien", 'Chien Finnois de Laponie',
  'Chien Loup Tchécoslovaque', 'Chien Loup de Saarloos',
  'Chihuahua', 'Chinook', 'Chow Chow', "Cirneco de l'Etna", 'Clumber Spaniel', 'Cockapoo', 'Cocker Américain', 'Cocker Anglais',
  'Colley (Lassie)', 'Coton de Tuléar', 'Croisé',
  'Dalmatien', 'Dandie Dinmont Terrier', 'Deerhound (Lévrier Écossais)', 'Doberman',
  'Dogue Allemand (Great Dane)', 'Dogue Argentin', 'Dogue de Bordeaux', 'Dogue des Canaries (Presa Canario)',
  'English Springer Spaniel',
  'Épagneul Breton', 'Épagneul de Pont-Audemer', 'Épagneul Français', 'Épagneul Münsterlander', 'Épagneul Papillon',
  'Eurasier',
  'Field Spaniel', 'Fila Brasileiro', 'Flat-Coated Retriever', 'Fox Terrier', 'Foxhound Anglais',
  'Galgo Espagnol', 'Gascon Saintongeois', 'Golden Retriever', 'Goldendoodle',
  'Grand Bleu de Gascogne', 'Grand Bouvier Suisse', 'Grand Griffon Vendéen',
  'Griffon Belge', 'Griffon Bruxellois', 'Griffon Fauve de Bretagne', 'Griffon Nivernais',
  'Hovawart', 'Husky Sibérien',
  'Irish Wolfhound (Lévrier Irlandais)',
  'Jack Russell Terrier', 'Jindo Coréen',
  "Kangal / Berger d'Anatolie", 'Keeshond (Spitz Loup)', 'Kelpie Australien', 'Komondor', 'Kooikerhondje', 'Kromfohrländer', 'Kuvasz',
  'Labradoodle', 'Labrador Retriever', 'Lagotto Romagnolo', 'Lakeland Terrier', 'Landseer', 'Leonberg',
  'Lévrier Afghan', 'Lévrier Azawakh', 'Lévrier de Pharaon', 'Lévrier (Greyhound / Whippet)', 'Lhasa Apso',
  'Maltais', 'Manchester Terrier', 'Mastiff Anglais',
  'Montagne des Pyrénées',
  'Norfolk Terrier', 'Norwich Terrier',
  'Pékinois', 'Petit Basset Griffon Vendéen', 'Petit Brabançon', 'Pinscher',
  'Podenco Canario', 'Podenco Ibicenco', 'Pointer', 'Puli', 'Pumi',
  'Retriever à Poil Bouclé', 'Retriever de la Nouvelle-Écosse', 'Rhodesian Ridgeback', 'Rottweiler',
  'Saint-Bernard', 'Saluki', 'Samoyède',
  'Schnauzer', 'Scottish Terrier', 'Sealyham Terrier', 'Setter Anglais', 'Setter Gordon', 'Setter Irlandais', 'Shar Pei',
  'Shiba Inu', 'Shih Tzu', 'Shikoku', 'Skye Terrier', 'Sloughi',
  'Spitz Finlandais', 'Spitz Japonais', 'Spitz (Poméranien)', 'Staffordshire Bull Terrier',
  'Teckel', 'Terre-Neuve', 'Terrier Australien', 'Terrier Irlandais', 'Terrier Kerry Blue', 'Terrier Tibétain', 'Tosa Inu',
  'Welsh Corgi Cardigan', 'Welsh Corgi Pembroke', 'Welsh Springer Spaniel', 'Welsh Terrier',
  'Westie (West Highland White Terrier)', 'Xoloitzcuintle (Chien Nu Mexicain)', 'Yorkshire Terrier', 'Autre race',
];
